import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import SidebarLayout from "@/component/Sidebar";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/authOptions";
import { redirect } from "next/navigation";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
 
  return (
    <html
      lang="en"
      className={`${inter.variable} h-full antialiased bg-[#FDF6F6]`}
    >
         <Toaster position="top-right" reverseOrder={false} />
      <body className=" flex gap-4 bg-[#FDF6F6]">
        <SidebarLayout />
        {children}
      </body>
    </html>
  );
}